FROM php:7.4.13-fpm-alpine3.12

LABEL maintainer="ahbanavi@gmail.com"
LABEL description="This image is 7.4.13-fpm-alpine3.12 with pdo_mysql installed"
LABEL version="1.0"

# Install pdo_mysql
RUN docker-php-ext-install pdo_mysql