name: Docker Image CI - Web3

on:
  push:
    branches: 
      - main
    paths:
      - 'Python/web3/Dockerfile'
      - 'Python/web3/requirements.txt'


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: Python/web3/
          push: true
          tags: ahbanavi/web3_py_tools:latest
          cache-from: type=registry,ref=ahbanavi/web3_py_tools:latest
          cache-to: type=inline
